GET http://127.0.0.1:3000/api/climbers/

###

POST http://127.0.0.1:3000/api/climbers/
Content-Type: application/json

{
    "name": "Will",
    "age": "14",
    "isMember": true,
    "geometry" : {"type": "point", "coordinates": [53.42, 42.42]}
}

### Test geolocation

GET http://127.0.0.1:3000/api/climbers/?lng=53.42&lat=42


###

PUT http://127.0.0.1:3000/api/climbers/60f2f89e0422d14b6c26b200
Content-Type: application/json

{
    "name": "David",
    "age": "13",
    "isMember": true
}
###

DELETE http://127.0.0.1:3000/api/climbers/60f2f8082b6a9c4d682f24af